x-amade-image: &amade-image ${AMADE_IMAGE:-ghcr.io/delta898/amade:0.1.0-rc.5}

services:
  amade:
    image: *amade-image
    working_dir: ${AMADE_WORKSPACE_DIR:-/amade/workspace}
    environment:
      AMADE_AUTH_STORE: docker-volume
      AMADE_CONFIG_DIR: ${AMADE_CONFIG_DIR:-/amade/config}
      AMADE_WORKSPACE_DIR: ${AMADE_WORKSPACE_DIR:-/amade/workspace}
      AMADE_TEMPLATE_DIR: ${AMADE_TEMPLATE_DIR:-/amade/templates}
      GH_CONFIG_DIR: /home/node/.config/gh
    ports:
      - "127.0.0.1:4321:4321"
    volumes:
      - type: bind
        source: ${AMADE_PROJECT_HOST_DIR:-./amade}
        target: ${AMADE_PROJECT_CONTAINER_DIR:-/amade}
      - type: bind
        source: ${AMADE_TEMPLATE_HOST_DIR:-./amade/templates}
        target: ${AMADE_TEMPLATE_DIR:-/amade/templates}
        read_only: true
      - type: volume
        source: amade-node-modules
        target: ${AMADE_WORKSPACE_DIR:-/amade/workspace}/node_modules
      - type: volume
        source: amade-auth
        target: /home/node/.config/.wrangler
      - type: volume
        source: amade-github-auth
        target: /home/node/.config/gh

volumes:
  amade-node-modules:
  amade-auth:
  amade-github-auth:
